platform :ios, '10.0'
target 'BaseProject' do

    pod 'AFNetworking'
    pod 'Reachability'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'FMDB'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'SAMKeychain'

    pod 'UITableView+FDTemplateLayoutCell'
    pod 'FDFullscreenPopGesture'

    pod 'Bugly'
    pod 'MLeaksFinder'
    #pod 'FBRetainCycleDetector'
    #pod 'FBMemoryProfiler'
    
    #pod 'YYKit'
    pod 'YYModel'
    pod 'YYCache'
    pod 'YYImage'
    pod 'YYWebImage'
    pod 'YYText'
    pod 'YYKeyboardManager'
    pod 'YYDispatchQueuePool'
    pod 'YYAsyncLayer'
    pod 'YYCategories'

    #pod 'ReactiveCocoa'

    #pod 'YTKNetwork'
    #pod 'hpple'                #html解析工具 从web前端的html里获取数据
    #pod 'KTVHTTPCache'         #唱吧iOS音视频在线播放缓存框架
    #pod 'FreeStreamer'
    #pod 'IQKeyboardManager'
    #pod 'SSZipArchive'
    #pod 'FLEX'
    #pod 'CocoaAsyncSocket'
    #pod 'lottie-ios'
    #pod 'SkeletonView'
	
end
