platform :ios, '8.0'
target 'BaseProject' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'YTKNetwork'
    pod 'MJExtension'
    pod 'Reachability'
    pod 'IQKeyboardManager'
    pod 'SSZipArchive'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'FDFullscreenPopGesture'
    pod 'hpple'
    pod 'KTVHTTPCache'

    pod 'YYModel'
    pod 'YYCache'
    pod 'YYImage'
    pod 'YYWebImage'
    pod 'YYText'
    pod 'YYKeyboardManager'
    pod 'YYDispatchQueuePool'
    pod 'YYAsyncLayer'
    pod 'YYCategories'
    
    pod 'MLeaksFinder'
    pod 'Bugly'
    #pod 'FLEX'


    #pod 'FreeStreamer'
    #pod 'YYKit'

end
