//
//  BPFoundationCategory.h
//  BaseProject
//
//  Created by xiaruzhen on 2017/12/10.
//  Copyright © 2017年 cactus. All rights reserved.
//

#ifndef BPFoundationCategory_h
#define BPFoundationCategory_h

#import "NSArray+BPBlock.h"
#import "NSArray+BPSafeAccess.h"
#import "NSBundle+BPAppIcon.h"
#import "NSData+BPAPNSToken.h"
#import "NSData+BPBase64.h"
#import "NSData+BPDataCache.h"
#import "NSData+BPEncrypt.h"
#import "NSData+BPGzip.h"
#import "NSData+BPHash.h"
#import "NSData+BPzlib.h"
#import "NSData+BPPCM.h"
#import "NSDate+BPCupertinoYankee.h"
#import "NSDate+BPExtension.h"
#import "NSDate+BPFormatter.h"
#import "NSDate+BPInternetDateTime.h"
#import "NSDate+BPReporting.h"
#import "NSDate+BPUtilities.h"
#import "NSDate+BPZeroDate.h"
#import "NSDate+BPLunarCalendar.h"
#import "NSDateFormatter+BPMake.h"
#import "NSDecimalNumber+BPCalculatingByString.h"
#import "NSDecimalNumber+BPExtensions.h"
#import "NSDictionary+BPBlock.h"
#import "NSDictionary+BPJSONString.h"
#import "NSDictionary+BPMerge.h"
#import "NSDictionary+BPSafeAccess.h"
#import "NSDictionary+BPURL.h"
#import "NSDictionary+BPXML.h"
#import "NSException+BPTrace.h"
#import "NSFileHandle+BPReadLine.h"
#import "NSFileManager+BPPaths.h"
#import "NSHTTPCookieStorage+BPFreezeDry.h"
#import "NSIndexPath+BPOffset.h"
#import "NSInvocation+BPBb.h"
#import "NSInvocation+BPBlock.h"
#import "NSMutableURLRequest+BPUpload.h"
#import "NSNotificationCenter+BPMainThread.h"
#import "NSNumber+BPCGFloat.h"
#import "NSNumber+BPRomanNumerals.h"
#import "NSNumber+BPRound.h"
#import "NSObject+BPAddProperty.h"
#import "NSObject+BPAppInfo.h"
#import "NSObject+BPAssociatedObject.h"
#import "NSObject+BPAutoCoding.h"
#import "NSObject+BPBlocks.h"
#import "NSObject+BPBlockTimer.h"
#import "NSObject+BPEasyCopy.h"
#import "NSObject+BPGCD.h"
#import "NSObject+BPKVOBlocks.h"
#import "NSObject+BPReflection.h"
#import "NSObject+BPRuntime.h"
#import "NSRunLoop+BPPerformBlock.h"
#import "NSSet+BPBlock.h"
#import "NSString+BPBase64.h"
#import "NSString+BPContains.h"
#import "NSString+BPDictionaryValue.h"
#import "NSString+BPEmoji.h"
#import "NSString+BPEncrypt.h"
#import "NSString+BPHash.h"
#import "NSString+BPMatcher.h"
#import "NSString+BPMIME.h"
#import "NSString+BPNormalRegex.h"
#import "NSString+BPPinyin.h"
#import "NSString+BPRemoveEmoji.h"
#import "NSString+BPScore.h"
#import "NSString+BPSize.h"
#import "NSString+BPTrims.h"
#import "NSString+BPURLEncode.h"
#import "NSString+BPUUID.h"
#import "NSString+BPXMLDictionary.h"
#import "NSString+BPStringPages.h"
#import "NSString+BPHTML.h"
#import "NSTimer+BPAddition.h"
#import "NSTimer+BPBlocks.h"
#import "NSURL+BPParam.h"
#import "NSURL+BPQueryDictionary.h"
#import "NSURLConnection+BPSelfSigned.h"
#import "NSURLRequest+BPParamsFromDictionary.h"
#import "NSURLSession+BPSynchronousTask.h"
#import "NSUserDefaults+BPiCloudSync.h"
#import "NSUserDefaults+BPSafeAccess.h"

#endif /* BPFoundationCategory_h */
